### ISSUE TITLE
能够提供模型的下载码

### ISSUE THREAD

**Issue by betterhalfwzm** [jiefengpeng/DNA#1]
谢谢

**Comment by jiefengpeng** [comment]
已提供云盘下载链接：https://drive.google.com/drive/folders/1Oqc2gq8YysrJq2i6RmPMLKqheGfB9fWH

**Comment by betterhalfwzm** [comment]
@jiefengpeng 谢谢分享。请问在目标检测coco或者voc数据集上做过实验吗？精度如何？

**Comment by jiefengpeng** [comment]
目前还没在检测任务上测试，后续工作会加上。

**Comment by betterhalfwzm** [comment]
@jiefengpeng 好的，谢谢，期待检测的结果
