### ISSUE TITLE
请问cifar-10迁移学习的那个模型，是直接使用DNA-c模型迁移的吗？

### ISSUE THREAD

**Issue by 5663015** [jiefengpeng/DNA#2]
DNA-c模型有5次下采样，cifar-10最后会被压缩为1x1大小的，请问是这样做的吗，谢谢！

**Comment by jiefengpeng** [comment]
我们采用与谷歌EfficientNet一致的迁移方法法，将CIFAR10 resize到(224, 224)再输入网络，所以5次下采样之后是(7, 7). 详情可参考：
Kornblith, S., Shlens, J., and Le, Q. V. Do better imagenet models transfer better? CVPR, 2019.
