### ISSUE TITLE
Which version is timm used?

### ISSUE THREAD

**Issue by 5663015** [jiefengpeng/DNA#5]
Could you bring out the specific version of timm? Thank you!

**Comment by jiefengpeng** [comment]
We test with timm==0.1.14. It is the leatest version.

**Comment by 5663015** [comment]
But there is no "GenEfficientNet" Class in timm 0.1.14 ?

**Comment by jiefengpeng** [comment]
Oops, It seems the author has resconstructed the code and rm the <class 'timm.models.gen_efficientnet.GenEfficientNet'>. But I can still import it with `pip install timm`. Make sure you did not import it from the repo directly.

**Comment by 5663015** [comment]
I have used other implement in my code. Thank you very much for your reply!

**Comment by jiefengpeng** [comment]
Welcome :)
